# ==================== APPLICATION ====================
spring.application.name=lab4

# ==================== POSTGRESQL DATABASE ====================
# PostgreSQL ?? localhost, ???? 5432, ???? ?????? bookdb
spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.username=postgres
spring.datasource.password=999111
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ==================== JPA / HIBERNATE ====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# ==================== SQL INITIALIZATION ====================
# ???? ?????? ???????????? schema.sql ? data.sql
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# ==================== WEB / MVC ====================
server.port=8080
server.servlet.context-path=/

# Static resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Content Negotiation (JSON/XML)
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false

# UTF-8 Encoding
spring.web.resources.encoding.charset=UTF-8
spring.web.resources.encoding.enabled=true
spring.web.resources.encoding.force=true

# ==================== LOGGING ====================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=audit.queue,notification.queue
spring.artemis.embedded.server-id=1
spring.artemis.embedded.data-directory=./target/artemis-data

# ????????? ??????????? ??? embedded ??????
spring.jms.cache.enabled=false

# Mail.ru SMTP - ???? 587 ? STARTTLS (??? ? ????? Python-??????????)
spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=yegor.sibryayev@mail.ru
spring.mail.password=01fOsSgM8Ri9nVc8M7W2
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ??? ???????
spring.mail.debug=true
logging.level.org.springframework.mail=DEBUG

